### ISSUE TITLE
Issue on server

### ISSUE THREAD

**Issue by bartdebever** [Lordmau5/The-Kappa-Experience#1]
Server wont start with the mod in it getting an error
http://pastebin.com/8vijY7wz

This is running v2.3 for 1.7.10 on a cauldron and modpack

**Comment by Lordmau5** [comment]
Please don't install the mod on the server-side.
Quote from the Curseforge page:
![Omg](http://lordmau5.com/ss/05-04-2015_16-52-54.png)

**Comment by bartdebever** [comment]
*Faceplant* my appologies
