### ISSUE TITLE
Few tips for curseforge.

### ISSUE THREAD

**Issue by Claycorp** [Lordmau5/The-Kappa-Experience#2]
Hey! This is an awesome idea and makes things quite funny especially when you play with people that are from twitch.

Though I noticed your curseforge page is a bit messy. If i were you i would remove all of the changelogs from the main page and attach them to the files when you upload it. Also inside the settings tab there are some useful options like the Issues header button. I highly recommend that you use those quick links instead of putting it in the post.

Keep up the good work! Don't want a messy post confusing people! If you have any questions feel free to ask me.

**Comment by Lordmau5** [comment]
*The Kappa Experience* is dead.
If you still want to use Emotes in Minecraft, please consider using *EiraMoticons* by @blay09 
http://minecraft.curseforge.com/mc-mods/230849-eiramoticons
