### ISSUE TITLE
Linewrapping ultry-hype issues

### ISSUE THREAD

**Issue by blay09** [Lordmau5/The-Kappa-Experience#6]
https://twitter.com/ZeekDaGeek/status/591949736338333696

This is not caused by EiraIRC

**Comment by Lordmau5** [comment]
I checked to reproduce that with the *exact same* String.
I couldn't.

![Img](http://ss.lordmau5.com/03-05-2015_22-44-03.png)

So for now, this is closed.
If it occurs again, I'll have to revamp the line-splitting... *again*...
