### ISSUE TITLE
Game crash in startup

### ISSUE THREAD

**Issue by Bogdan-G** [Lordmau5/The-Kappa-Experience#8]
Hello. MC 1.7.10, Forge 1403, Fastcraft, Optifine, etc
crash-report - https://gist.github.com/Bogdan-G/290dabef592b0c5f4ac1
full-fml-log - https://gist.github.com/Bogdan-G/2a65517d285b36b1815c

**Comment by Lordmau5** [comment]
*The Kappa Experience* is dead.
If you still want to use Emotes in Minecraft, please consider using *EiraMoticons* by @blay09 
http://minecraft.curseforge.com/mc-mods/230849-eiramoticons
