### ISSUE TITLE
Achievement Mouseovers broken after installing The Kappa Experience

### ISSUE THREAD

**Issue by SephirothWS** [Lordmau5/The-Kappa-Experience#9]
After installing The Kappa Experience into an instance with 152 mods, getting an achievement works just fine. However, mousing over the achievement text in the game's chat window to view a description of the achievement no longer works. Plus the formatting of these things are completely busted when they go to a new line.

![image](http://i.imgur.com/Ji9h8Sz.jpg)

**Comment by Lordmau5** [comment]
*The Kappa Experience* is dead.
If you still want to use Emotes in Minecraft, please consider using *EiraMoticons* by @blay09 
http://minecraft.curseforge.com/mc-mods/230849-eiramoticons
